name             "apptentive_gradle"
maintainer       "Apptentive, Inc."
maintainer_email "blake@apptentive.com"
license          "mit"
description      "Installs gradle"
long_description "Installs gradle"
version          "0.1.0"
